---
# 📁 Hyun's Code collection (Pandas) 
---

### <h3 align="right">🥇 Authored by <strong>Hyun</strong></h3>

# ✏️  What is **Numpy**?

- Numpy는 Python의 고성능 과학 계산용 패키지
-  Matrix와 Vector와 같은 array 연산의 사실상의 표준
- [Numpy 설명](https://numpy.org) 

# ✏️ Importing Libraries

In [ ]:
# Basic Setting
import numpy as np
from numpy.linalg import inv
from numpy.linalg import solve
import random

# ✏️  Methods and Examples

## 🔎 Basic Methods

- **.size ( )**: 개수
- **.sum ( )**: 합
- **.mean ( )**: 평균
- **.median ( )**: 중앙값
- **.std ( )**: 표준편차
- **.max ( )**: 최대값
- **.min ( )**: 최소값
- **.inv ( )**: 역행렬을 만들어줌
- **solve( , )**: 해를 구해줌
- **argsort( )**: 제일 작은 값을 찾아줌
<br>

- **np.array ( [ list ], type )**: array 생성. type에는 int, float 등이 올 수 있음
- **type ( )**: type을 보여준다
- **.shpae** : array의 shape을 반환
- **.ndim**: 차원을 반환
- **.size**: 데이터의 개수를 반환

- **.nbytes**: 메모리의 크기를 반환
- **.reshape**: 주어진 행렬 shape에 맞게 변환
- **.flatten ( )**: matrix를 1차원으로 반환
- **.flat ( )**: matrix를 1차원으로 반환
- **.tolist ( )**: 리스트로 변환
- **.transpose ( )**: transpose 시킨다.
- **.T**: 이렇게도 사용 가능!
- **.sum ( axis = )**: axis를 지정 안하면 해당 vector를 합하고 axis를 정해주면 각 axis별로 합한 값을 반환
- **.mean ( axis = )**: sum과 유사. 평균값을 반환
- **.dot ( )**: 앞에 행렬과 뒤의 행렬을 내적
- **.all ( cond )**: 조건에 1개라도 참이면 True를 반환
- **.any ( cond )**: 조건에 모두 참이어야 True를 반환
- **+, - , * :** Matrix간의 연산
- **< , > , == :** array들간의 비교
<br>

- **np .sqrt ( )**: 가로값에 루트를 씌움  
- **np .sin ( )**: 가로값에 sin를 씌움 
- **np .cos ( )**: 가로값에 cos를 씌움
- **np .tan ( )**: 가로값에 tan를 씌움
- **np .log ( )**: 가로값에 log를 씌움 
- **np .argmax ( )**: 최대값의 index를 반환
- **np .argmin ( )**: 최소값의 index을 반환
- **np .max ( )**: 최대값을 반환
- **np .min ( )**: 최소값을 반환
- **np .arange ( int )**: 0부터 (int-1)만큼 간격이 1인 정수를 반환
- **np .arange ( 시작 , 끝 , 간격 )**: 시작부터 끝까지 주어진 간격만큼 숫자를 반환
- **np .linspace ( a , b, num )**: a<= x <=b에서 균등한 거리로 num개의 숫자를 추출
- **np .zeros ( shape = ( , ) , dtype = )**: 해당 shape의 0 행렬을 반환
- **np .zeros_like ( ndarray )**: ndarray 행렬에 해당하는 0 행렬을 반환
- **np .ones ( shape = ( . ), dtype = )**: 해당 shaep의 1 행렬을 반환
- **np .ones_like ( ndarray )**: ndarray 행렬과 동일한 shape을 가진 1 행렬 생성
- **np .empty ( shape = ( , ), dtype = )**: 해당 shape의 0 행렬을 반환
- **np .empty_like ( ndarray ))**: 해당 shape과 같은 shape의 0 행렬 생성
- **np .identity ( n = , dtype = np. )**: n*n 항등행렬을 만들어줌
- **np .eye ( N = , M = , dtype = np. )**: row, column의 shape에 [0,0]에서 diagonal이 시작하는 행렬 반환
- **np .eye ( , , k = )**: 주어진 shape의 행렬을 생성 후 k로 대각행렬의 시작 index를 지정
- **np .full ( shape, num )**: 주어진 shape의 행렬에 num으로 가득 찬 행렬을 생성
- **np .diag ( ndarray )**: 주어진 ndarray의 대각행렬의 값을 추출

  **np .diag ( , k = )**: 주어진 행렬에 대각성분을 vector 형식으로 반환, k로 index 지정
- **np .seed ( )**: seed값을 설정. 난수를 발생시킨다는 것은 어떤 계산된 과정에 의한 것이다. 즉, seed값이 같다면 같은 난수를 발생시킬 수 있음
- **np .random .sample ( min , max , 개수)**: 범위내에서 무작위로 주어진 개수만큼 정수를 추출. 비복원추출
- **np .random .choics ( min , max , 개수)**: 범위내에서 무작위로 주어진 개수만큼 정수를 추출. 복원추출
- **np .random .rand ( shape )**: 입력한 shape의 형태로 [0, 1]에 해당하는 random 값들을 반환
- **np .random .randn ( shape )**: shape에 해당하는 평균 0, 표준편차 1인 정규분포를 생성
- **np .random .uniform ( low , high ,size =  )**: size에 해당하는 정규분포값을 반환
- **np .random .normal ( mean , std , size(개수) )**: 정규분포에서 무작위 값을 추출함
- **np .random .randint ( 최소, 최대, size = num )**: shape을 지정하는 대신 최소, 최대 값을 설정 가능
- **np .nan**: NaN값을 생성
- **np .random .choice ( a, size = None , replace = True , p = None )** : 데이터 샘플링하기. a는 원래 데이터 or arange(a), size는 샘플 개수, replace는 중복 허용, p는 뽑힐 확률
- **np .random .permutation ( )**: 배열이 저장된 변수자체를 변경하는게 아니라, 랜덤으로 섞은 배열만을 다시 반환

<br>

- **np .linalg**
- **np .linalg .inv( )**: 역행렬 계산

<br>

- **np .vstack ( ( a , b ) )**: Vertically stack arrays
- **np .hstack ( ( a , b ) )**: Horizontally stack arrays
- **np .concatenate ( ( , ) , axis = )**: 2개의 vector 혹은 matrix를 axis에 따라서 concat해줌
<br>

- **np .where ( condition, if True , if False )**: 조건에 따라서 값들을 반환
- **np .isnan ( )**: boolean 형태로 결측치를 반환
- **np .isfinite ( )**: 유한수의 여부에 따라서 boolean 형태로 값을 반환
- **np .ceil( )**: 각 원소 값보다 크거나 같은 가장 작은 정수 값(천장 값)으로 올림

- **np .leadtxt ( " " )**: directory와 파일이름을 입력
- **np .save (" ", arr = )**: txt로 저장하기
- **broadcasting**: broadcasting은 어떤 조건만 만족한다면 모양이 다른 배열끼리의 연산도 가능하게 해주며 모양이 부족한 부분은 확장하여 연산을 수행할 수 있도록 한다는 것
- **boolean index**: 조건에 맞아서 True인 값들을 indexing하는 방법

### 📔 Examples

In [ ]:
# 원하는 array를 만들어주는 방법
list_phrases = []
empty_vector = np.zeros(shape=(1795,100))
for phrase in phrase_json:
    empty_vector[int(phrase)-1] = np.array(phrase_json[phrase]['vector'])
    list_phrases.append(phrase_json[phrase]['phrase_id'])

In [ ]:
# argsort
np.argsort(rmse_val_score)

In [ ]:
# solve
x = solve(A,b)    # A는 계수, b는 타겟 vector

In [ ]:
# inv()
A_inv = inv(A)

In [ ]:
# np.zeros
a = np.zeros((2,2), dtype=int)
a

array([[0, 0],
       [0, 0]])

In [ ]:
# broadcasting
## 예시2
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

test_matrix + scalar # Matrix - Scalar 덧셈

test_matrix - scalar # Matrix - Scalar 뺄셈

test_matrix * 5 # Matrix - Scalar 곱셈

test_matrix / 5 # Matrix - Scalar 나눗셈

test_matrix // 0.2 # Matrix - Scalar 몫

test_matrix ** 2 # Matrix - Scalar 제곱

## 예시2
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
test_matrix + test_vector

In [ ]:
# np.array
test_array = np.array(["1", "4", 5, 8], float)    # String type을 입력해도 Float Type으로 자동 형변환 실시
test_array

In [ ]:
# type
type(test_array[3])

In [ ]:
# .shape
print(np.array([[1, 4, 5, "8"]], np.float32).shape)

vector  = [1,2,3,4]
print(np.array(vector, int).shape)

In [ ]:
# .shape: Array shape
matrix  = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

In [ ]:
# .shape, .ndim, .size
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
print(np.array(tensor, int).shape)
print(np.array(tensor, int).ndim)    # 차원 반환
print(np.array(tensor, int).size)    # 데이터의 개수를 반환

In [ ]:
# .nbytes
a = np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.float32)
print(a.nbytes)

b = np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.int8)
print(b.nbytes)

c = np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.float64)
print(c.nbytes)

In [ ]:
# .reshape
## 예제1
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape
np.array(test_matrix).reshape(2,2,2)

## 예제2
np.array(test_matrix).reshape(2,4).shape

## 예제3
np.array(test_matrix).reshape(2,-1).shape

## 예제4
np.array(test_matrix).reshape(2,2,2)

## 예제5
np.array(test_matrix).reshape(2,2,2).shape

## 예제6
test = np.array(test_matrix).reshape(8,)
test
test.reshape(-1, 1)

In [ ]:
# .flatten()
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

In [ ]:
# indexing
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

## 예제1
test_exmaple[0][0]

## 예제2
test_exmaple[1,2]

## 예제3
test_exmaple[0,0] = 10 # Matrix 0,0 에 12 할당
test_exmaple

In [ ]:
# slicing
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple.shape

## 예제1
test_exmaple[:,1:3] 
test_exmaple[1,:2]

## 예제2
test_exmaple = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_exmaple[:,2:] # 전체 Row의 2열 이상

## 예제3
test_exmaple[1,1:3] # 1 Row의 1열 ~ 2열

## 예제4
test_exmaple[1:3] # 1 Row ~ 2Row의 전체

In [ ]:
import numpy as np

In [ ]:
# np.arange
## 예제1
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
np.arange(30).reshape(-1,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
np.arange(30).reshape(3,-1)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
# np.arange
## 예제1
a = np.arange(100).reshape(10,10)
a

a[:, -1].reshape(-1,1)

## 예제1
np.arange(30).reshape(-1,5)

## 예제2
np.arange(0, 5, 0.5)

## 예제3
np.arange(30).reshape(5,6)

In [ ]:
# np.zeros, np.ones, np.empty, np.zeros_like
## 예제1
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

## 예제2
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

## 예제3
np.ones(shape=(10,), dtype=np.int8)

## 예제4
np.ones((2,5))

## 예제5
np.empty(shape=(10,), dtype=np.int8)

## 예제6
np.empty((3,5))

## 예제7
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)

In [ ]:
# np.identity, np.eye, np.diag
## 예제1
np.identity(n=3, dtype=np.int8)

## 예제2
np.identity(5)

## 예제3
np.eye(N=3, M=5, dtype=np.int8)

## 예제4
np.eye(3)

## 예제5
np.eye(3,5,k=2)

## 예제6
matrix = np.arange(9).reshape(3,3)
np.diag(matrix), np.diag(matrix, k=1)

In [ ]:
# .sum()
## 예제1
test_array = np.arange(1,11)
test_array.sum(dtype=np.float)

## 예제2
test_array = np.arange(1,13).reshape(3,4)
test_array

test_array.sum(axis=1)
test_array.sum(axis=0)

## 예제3
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

third_order_tensor.sum(axis=0)
third_order_tensor.sum(axis=1)
third_order_tensor.sum(axis=2)

## 예제4
test_array = np.arange(1,13).reshape(3,4)
test_array

test_array.mean(), test_array.mean(axis=0)

## 예제5
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a + test_a # Matrix + Matrix 연산
test_a - test_a # Matrix - Matrix 연산
test_a * test_a # Matrix내 element들 간 같은 위치에 있는 값들끼리 연산

In [ ]:
# np.vstack(), np.hstack(), np.concatenate, 
## 예제1
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

## 예제2
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

## 예제3
a = np.array([[1, 2]])
b = np.array([[2, 3]])
np.concatenate( (a,b) ,axis=0)

## 예제4
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate( (a,b.T) ,axis=1)    # .T: transpose

In [ ]:
# .tolist
a = np.array([[1, 2], [3, 4]])
a.tolist()

In [ ]:
# .dot
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

test_a.dot(test_b)

In [ ]:
# .transpose(), .T
test_a = np.arange(1,7).reshape(2,3)
test_a.transpose()
test_a.T

In [ ]:
# .any(), .all()
## 예시1
a = np.arange(10)
np.any(a>5), np.any(a<0)
np.all(a>5) , np.all(a < 10)

In [ ]:
# array들간의 비교
## 예시1
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)

test_a ,test_b
test_a == test_b
test_a > test_b
(test_a > test_b).any()

In [ ]:
# np.where()
## 예제1
a = np.arange(10)
np.where(a < 5, a, 10*a)

## 예제2
np.where(a>5)

In [ ]:
# np.argmax(), np.argmin()
## 예시1
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)

## 예시2
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

In [ ]:
# boolean index
## 예시1
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

test_array[test_array > 3]

condition = test_array < 3 
test_array[condition]

In [ ]:
# np.loadtxt(), np.load
## 예시1
a = np.loadtxt("./populations.txt")
a[:10]

## 예시2
npy_array = np.load(file="npy_test.npy")
npy_array[:3]